AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon Route53 Application Recovery Controller cluster and routing control for the Tic Tac Toe Demo app'
Parameters:
  Region1:
    Default: us-east-1
    Description: The region for the first cell
    Type: String 

  Region2:
    Default: us-west-2
    Description: The region for the second cell
    Type: String 

  ProjectId:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric
      characters.
    Default: TicTacToe
    Description: The name of the project
    MaxLength: '64'
    MinLength: '1'
    Type: String

Resources:
  Cluster:
    Type: AWS::Route53RecoveryControl::Cluster
    Properties:
      Name: !Sub ${ProjectId}-Cluster

  ControlPanel:
    Type: AWS::Route53RecoveryControl::ControlPanel
    Properties:
      Name: !Sub ${ProjectId}-ControlPanel
      ClusterArn: !Ref Cluster

  RoutingControlCell1:
    Type: AWS::Route53RecoveryControl::RoutingControl
    Properties:
      Name: !Sub ${ProjectId}-Cell1-${Region1}
      ClusterArn: !Ref Cluster
      ControlPanelArn: !Ref ControlPanel
 
  RoutingControlCell2:
    Type: AWS::Route53RecoveryControl::RoutingControl
    Properties:
      Name: !Sub ${ProjectId}-Cell2-${Region2}
      ClusterArn: !Ref Cluster
      ControlPanelArn: !Ref ControlPanel

  SafetyRuleMinCellsActive:
    Type: AWS::Route53RecoveryControl::SafetyRule
    Properties:
      Name: !Sub ${ProjectId}-MinCellsActive
      ControlPanelArn: !Ref ControlPanel
      AssertionRule:
        WaitPeriodMs: 5000
        AssertedControls:
          - !Ref RoutingControlCell1
          - !Ref RoutingControlCell2
      RuleConfig:
        Type: ATLEAST
        Threshold: 1
        Inverted: false

  # SafetyRuleAssertionCanary:
  #   Type: AWS::Route53RecoveryControl::SafetyRule
  #   Properties:
  #     Name: !Sub ${ProjectId}-SafetyRuleAssertionCanary
  #     ControlPanelArn: !Ref ControlPanel
  #     AssertionRule:
  #       WaitPeriodMs: 10
  #       AssertedControls: 
  #         - !Ref RoutingControlCell1
  #         - !Ref RoutingControlCell2
  #     RuleConfig:
  #       Type: OR
  #       Threshold: 5
  #       Inverted: False

Outputs:
  ClusterArn:
    Value: !Ref Cluster

  